<%@ Page Title="" Language="C#" MasterPageFile="~/MP.Master" AutoEventWireup="true" CodeBehind="AboutUs.aspx.cs" Inherits="WebApplication2.AboutUs" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link href="../css/Main.css" type="text/css" rel="stylesheet" />
    <link href="../css/contact.css" type="text/css" rel="stylesheet" />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentBody" runat="server">

     <div class="description">
        ABOUT US

<p>Welcome to Homemade Furniture, our company have started since 2011 as a small busniess. As time pass through our company eventually grew larger and larger towards a point where we are facing geographical limitations in expanding the business thus an official website for Homemade Furniture is made.
Homemade Furniture is more than just a place to find great deals on furniture and decor. We're also here to help you out with ideas, inspiration and practical tips to help you create the home you want. The reason for this website was made due to an increase in demands for homemade furniture due to quality, creative design and function.</p>
        <p>Ever since we have an increase in demands, we decided to further or expand our company by doing some online orders.</p>
   <p>Muebles se refiere a objetos movibles destinados a soportar diversas actividades humanas tales como asientos (por ejemplo, sillas, taburetes y sofás), comer (tablas) y dormir (por ejemplo, camas). Los muebles también se utilizan para sujetar objetos a una altura conveniente para el trabajo (como superficies horizontales sobre el suelo, como mesas y escritorios), o para almacenar cosas (por ejemplo, armarios y estantes). Muebles pueden ser un producto de diseño y se considera una forma de arte decorativo. Además de la función funcional de los muebles, puede servir un propósito simbólico o religioso. Se puede hacer de muchos materiales, incluyendo el metal, el plástico, y la madera. Los muebles se pueden hacer usando una variedad de empalmes de la madera que reflejan a menudo la cultura local.

La gente ha estado usando objetos naturales, como tocones, rocas y musgos, como muebles desde el comienzo de la civilización humana. La investigación arqueológica muestra que hace alrededor de 30.000 años, la gente comenzó a construir y tallar sus propios muebles, utilizando madera, piedra y huesos de animales. Los muebles tempranos de este período se saben de las ilustraciones tales como una estatuilla de Venus encontrada en Rusia, representando la diosa en un trono. Los primeros muebles que sobreviven son en los hogares de Skara Brae en Escocia, e incluye armarios, aparadores y camas construidas de piedra. Las técnicas de construcción complejas como la carpintería comenzaron en el período dinástico temprano del antiguo Egipto. Esta era vio piezas de madera construidas, incluyendo taburetes y mesas, a veces decoradas con metales valiosos o marfil. La evolución del diseño de muebles continuó en la antigua Grecia y la antigua Roma, con tronos que son comunes, así como el klinai, sofás polivalentes utilizados para relajarse, comer y dormir. Los muebles de la Edad Media solían ser pesados, robles y adornados. El diseño de muebles se expandió durante el Renacimiento italiano del siglo XIV y XV. El siglo XVII, tanto en el sur como en el norte de Europa, se caracterizó por los opulentos, a menudo dorados diseños barrocos. El siglo XIX se define generalmente por los estilos de renacimiento. Los primeros tres cuartos del vigésimo siglo se ven a menudo como la marcha hacia el modernismo. Una consecuencia única de diseño de muebles post-moderno es un retorno a las formas naturales y texturas.</p>
        <p>The practice of using natural objects as rudimentary pieces of furniture probably dates from the beginning of human civilization. [7] Early humans are likely to have used stumps as seats, rocks as rudimentary tables, and mossy sleeping areas. During the late Paleolithic or Early Neolithic period, about 30,000 years ago, people began to build and carve their own furniture, using wood, stone, and animal bones. The earliest evidence for the existence of constructed furniture is a Venus statuette found at the site of Gagarin in Russia, which depicts the goddess in a seated position, on a throne. A similar statue of a mother goddess was found at Catal Huyuk in Turkey, dating to between 6000 and 5500 BC. [7] The inclusion of such a seat in the figures implies that these were already common artifacts of that age. [9]


Skara Brae home furniture, a chest of drawers with shelves
A range of unique stone furniture has been excavated in Skara Brae, a Neolithic village in Orkney, Scotland. The site dates from 3100-2500 BC and because of the shortage of wood in Orkney, the people of Skara Brae were forced to build with stone, an easily available material that could be easily worked and converted into articles for use inside the house . Each house shows a high degree of sophistication and was equipped with a wide variety of stone furniture, ranging from cabinets, dressers and beds to shelves, stone seats and lapa tanks. The stone sideboard was considered as the most important, as it symbolically faces the entrance into each house and thus is the first element seen upon entering, perhaps the display of symbolic objects, including decorative works of art such as several Neolithic carved stone balls are also found on the site.

Ancient furniture has been excavated from the 8th century BC phrygian tumulus, the Midas Mound, in Gordion, Turkey. The pieces found here include tables and engraved prints. There are also surviving works of the Assyrian palace of Nimrud, eighth and eighth century. The Pazyryk Carpet was discovered in a frozen tomb in Siberia and was dated between the 6th and 3rd centuries BC.</p>
        <p>The practice of using natural objects as rudimentary pieces of furniture probably dates from the beginning of human civilization. [7] Early humans are likely to have used stumps as seats, rocks as rudimentary tables, and mossy sleeping areas. During the late Paleolithic or Early Neolithic period, about 30,000 years ago, people began to build and carve their own furniture, using wood, stone, and animal bones. The earliest evidence for the existence of constructed furniture is a Venus statuette found at the site of Gagarin in Russia, which depicts the goddess in a seated position, on a throne. A similar statue of a mother goddess was found at Catal Huyuk in Turkey, dating to between 6000 and 5500 BC. [7] The inclusion of such a seat in the figures implies that these were already common artifacts of that age. [9]


Skara Brae home furniture, a chest of drawers with shelves
A range of unique stone furniture has been excavated in Skara Brae, a Neolithic village in Orkney, Scotland. The site dates from 3100-2500 BC and because of the shortage of wood in Orkney, the people of Skara Brae were forced to build with stone, an easily available material that could be easily worked and converted into articles for use inside the house . Each house shows a high degree of sophistication and was equipped with a wide variety of stone furniture, ranging from cabinets, dressers and beds to shelves, stone seats and lapa tanks. The stone sideboard was considered as the most important, as it symbolically faces the entrance into each house and thus is the first element seen upon entering, perhaps the display of symbolic objects, including decorative works of art such as several Neolithic carved stone balls are also found on the site.

Ancient furniture has been excavated from the 8th century BC phrygian tumulus, the Midas Mound, in Gordion, Turkey. The pieces found here include tables and engraved prints. There are also surviving works of the Assyrian palace of Nimrud, eighth and eighth century. The Pazyryk Carpet was discovered in a frozen tomb in Siberia and was dated between the 6th and 3rd centuries BC.</p>
         </div>
   

</asp:Content>
